#!/usr/bin/env python3
"""Emit src/app/sitemap.ts from canonical accessors (#1387).

Authorship moved from Phase A (state-11-core-scaffold) to state-11c post-fan-out
so dynamic-segment fixture slugs declared in experiment.yaml's
behaviors[*].dynamic_segments can be enumerated into the sitemap. Phase A
runs BEFORE fixture data exists; only state-11c has the full picture.

Consumes:
  - derive_scope_pages(experiment)         — static page slugs (sorted set)
  - dynamic_public_pages(experiment, repo) — concrete URL instances for
                                              dynamic-segment routes
                                              (e.g., /portfolio/<slug>)

Writes: src/app/sitemap.ts

Convention: URL field follows Next.js MetadataRoute.Sitemap shape. Base URL
derives from process.env.NEXT_PUBLIC_SITE_URL when set (production), else a
relative path (development). The generated file is deterministic given the
same experiment.yaml — re-running this script with no input changes yields
byte-identical output.

CLI:
    python3 .claude/scripts/lib/emit-sitemap.py [--experiment PATH]
                                                  [--out PATH]
                                                  [--repo-root PATH]
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from derive_pages import (  # type: ignore
    derive_page_set_for_design_critic,
    derive_scope_pages,
    dynamic_public_pages,
)


_SITEMAP_TEMPLATE = '''import type {{ MetadataRoute }} from 'next';

// Auto-generated by .claude/scripts/lib/emit-sitemap.py during bootstrap
// state-11c post-fan-out (#1387). DO NOT EDIT BY HAND — re-run the script
// after changing experiment.yaml behaviors or dynamic_segments.

function base() {{
  return process.env.NEXT_PUBLIC_SITE_URL ?? '';
}}

export default function sitemap(): MetadataRoute.Sitemap {{
  const now = new Date();
  const b = base();
{fixtures}  return [
{entries}
  ];
}}
'''


def _literal_entry(path: str, priority: float) -> str:
    return (
        f"    {{ url: `${{b}}{path}`, lastModified: now, "
        f"changeFrequency: 'weekly' as const, priority: {priority:.1f} }},"
    )


def _fixture_const_name(page: str, segment: str) -> str:
    """Return a TS const name for a (page, segment) fixture array.

    E.g., ('portfolio-slug', 'slug') -> 'PORTFOLIO_SLUG_FIXTURES'.
    E.g., ('v-variant', 'variant')   -> 'V_VARIANT_FIXTURES'.
    """
    import re as _re
    slug = _re.sub(r"[^a-zA-Z0-9]+", "_", page).strip("_").upper()
    return f"{slug}_FIXTURES"


def emit(experiment: dict[str, Any], repo_root: str = ".") -> str:
    """Render src/app/sitemap.ts contents as a string.

    Issue #1450 gap 3: route shape is sourced from
    derive_page_set_for_design_critic (the canonical filesystem walker
    that returns each page's concretized `test_url`). Previously the
    emitter wrote page-name-as-URL entries (e.g., /variant), producing
    invalid URLs when the actual route was /v/[variant]. The canonical
    helper hands us the resolved URL directly.

    Issue #1467: behavior_contract_auditor._sitemap_has_iteration (in
    behavior_contract_auditor.py:393-407) builds its regex from
    re.escape(<segment>) where <segment> is the contract's segment
    identifier (e.g., 'variant', 'slug', 'id', 'token'). Auditor accepts
    a sitemap.ts containing `.map((<segment>) => ...)` / `for (const
    <segment> of ...)` / `.forEach((<segment>) => ...)` and rejects
    sitemaps that emit only literal { url: ... } entries per fixture.

    To satisfy both _sitemap_has_iteration (auditor) and _sitemap_contains_slug
    (which greps for slug literals anywhere in the file), this emitter
    now groups dynamic_public_pages() entries by (page, segment) and
    emits a per-group const fixture array plus a spread-map call. The
    `.map()` arrow parameter is the segment identifier (e.g.,
    `.map((slug) => ...)`, `.map((variant) => ...)`) so the auditor's
    re.escape(segment) regex matches by construction. Slug literals
    appear inside the const fixture array, satisfying
    _sitemap_contains_slug.

    Static-route entries (canonical page set) remain literal { url: ... }
    objects — the auditor does not require iteration for non-dynamic
    pages.
    """
    static_entries: list[str] = []
    seen_urls: set[str] = set()

    def _add_static(url: str | None, priority: float) -> None:
        if not url or url in seen_urls:
            return
        seen_urls.add(url)
        static_entries.append(_literal_entry(url, priority))

    # Landing root — always present.
    _add_static("/", 1.0)

    # Canonical page set: one entry per page, with route resolved from
    # filesystem. Skip landing (already added).
    for entry in derive_page_set_for_design_critic(experiment, repo_root):
        if entry.get("name") == "landing":
            continue
        _add_static(entry.get("test_url"), 0.7)

    # Multi-value dynamic pages: group by (page, segment), emit a
    # const fixture array + .map() iteration block per group. Pre-mark
    # all concrete URLs as seen so the iteration entries are not also
    # emitted as literals by the dedup logic.
    dynamic_groups: dict[tuple[str, str], dict[str, Any]] = {}
    for entry in dynamic_public_pages(experiment, repo_root):
        concrete = entry.get("concrete_url")
        if not concrete:
            continue
        seen_urls.add(concrete)
        page = entry.get("page") or ""
        segment = entry.get("segment") or ""
        route_pattern = entry.get("route_pattern") or ""
        value = entry.get("value")
        if not page or not segment or not route_pattern or value is None:
            continue
        key = (page, segment)
        grp = dynamic_groups.setdefault(key, {
            "page": page,
            "segment": segment,
            "route_pattern": route_pattern,
            "values": [],
        })
        if value not in grp["values"]:
            grp["values"].append(value)

    fixture_decls: list[str] = []
    dynamic_entries: list[str] = []
    for (page, segment), grp in sorted(dynamic_groups.items()):
        const_name = _fixture_const_name(page, segment)
        values_repr = ", ".join(f'"{v}"' for v in grp["values"])
        fixture_decls.append(
            f"  const {const_name} = [{values_repr}] as const;"
        )
        # Convert "/portfolio/[slug]" -> "/portfolio/${slug}" template-literal form.
        # The arrow parameter MUST equal `segment` so the auditor's
        # re.escape(segment) regex matches the .map() call site.
        url_template = grp["route_pattern"].replace(
            f"[{segment}]", "${" + segment + "}"
        )
        dynamic_entries.append(
            "    ..." + const_name
            + f".map(({segment}) => ({{ url: `${{b}}{url_template}`, "
            "lastModified: now, "
            "changeFrequency: 'weekly' as const, priority: 0.6 })),"
        )

    entries_block = "\n".join(static_entries + dynamic_entries)
    fixtures_block = ("\n".join(fixture_decls) + "\n") if fixture_decls else ""
    return _SITEMAP_TEMPLATE.format(entries=entries_block, fixtures=fixtures_block)


def _load_experiment(path: str) -> dict[str, Any]:
    try:
        import yaml  # type: ignore
    except ImportError:
        sys.stderr.write("ERROR: PyYAML not installed (pip install pyyaml)\n")
        sys.exit(2)
    if not os.path.isfile(path):
        sys.stderr.write(f"ERROR: experiment.yaml not found at {path}\n")
        sys.exit(2)
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Emit src/app/sitemap.ts from canonical page accessors (#1387)."
    )
    parser.add_argument(
        "--experiment",
        default="experiment/experiment.yaml",
        help="Path to experiment.yaml (default: experiment/experiment.yaml).",
    )
    parser.add_argument(
        "--out",
        default="src/app/sitemap.ts",
        help="Output file (default: src/app/sitemap.ts).",
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Project root for dynamic_public_pages filesystem scan (default: cwd).",
    )
    parser.add_argument(
        "--print",
        action="store_true",
        help="Print to stdout instead of writing to disk.",
    )
    args = parser.parse_args()

    experiment = _load_experiment(args.experiment)
    contents = emit(experiment, args.repo_root)

    if args.print:
        sys.stdout.write(contents)
        return 0

    out_dir = os.path.dirname(args.out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(contents)
    print(f"emit-sitemap: wrote {args.out} ({contents.count('url:')} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
